const ADD_SCORE_VALUE = 30;
const ADD_COIN_VALUE = 50;
const LEADER_TOP_BUTTOM = 100;
const ADD_COIN_VALUE_EQUAL = 20;
const ADD_COIN_GIFT = 200;

module.exports = {
  ADD_SCORE_VALUE,
  ADD_COIN_VALUE,
  LEADER_TOP_BUTTOM,
  ADD_COIN_VALUE_EQUAL,
  ADD_COIN_GIFT
}
